---
name: "Release"

on:
  push:
    branches:
      - master
      - develop
      - test-feature
    paths-ignore:
      - '**/README.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/exec
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
